'use strict';
// oui.js - MAC OUI prefix → device type + vendor name
// Top manufacturers covering ~80% of home network devices

const OUI_MAP = [
  // Apple
  { prefix: '00:03:93', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:0a:27', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:0a:95', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:0d:93', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:11:24', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:14:51', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:16:cb', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:17:f2', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:19:e3', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:1b:63', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:1c:b3', vendor: 'Apple',   type: 'phone'    },
  { prefix: '00:1e:52', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:1e:c2', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:1f:5b', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:1f:f3', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:21:e9', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:22:41', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:23:12', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:23:32', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:23:6c', vendor: 'Apple',   type: 'phone'    },
  { prefix: '00:24:36', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:25:00', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:25:4b', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:25:bc', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:26:08', vendor: 'Apple',   type: 'phone'    },
  { prefix: '00:26:b9', vendor: 'Apple',   type: 'computer' },
  { prefix: '00:26:bb', vendor: 'Apple',   type: 'computer' },
  { prefix: '28:37:37', vendor: 'Apple',   type: 'phone'    },
  { prefix: '2c:f0:ee', vendor: 'Apple',   type: 'phone'    },
  { prefix: '34:08:bc', vendor: 'Apple',   type: 'phone'    },
  { prefix: '3c:07:54', vendor: 'Apple',   type: 'phone'    },
  { prefix: '3c:2e:ff', vendor: 'Apple',   type: 'computer' },
  { prefix: '40:30:04', vendor: 'Apple',   type: 'computer' },
  { prefix: '40:33:1a', vendor: 'Apple',   type: 'phone'    },
  { prefix: '44:00:10', vendor: 'Apple',   type: 'computer' },
  { prefix: '48:43:7c', vendor: 'Apple',   type: 'phone'    },
  { prefix: '4c:57:ca', vendor: 'Apple',   type: 'computer' },
  { prefix: '54:26:96', vendor: 'Apple',   type: 'phone'    },
  { prefix: '58:55:ca', vendor: 'Apple',   type: 'phone'    },
  { prefix: '60:03:08', vendor: 'Apple',   type: 'computer' },
  { prefix: '60:f8:1d', vendor: 'Apple',   type: 'phone'    },
  { prefix: '64:a3:cb', vendor: 'Apple',   type: 'phone'    },
  { prefix: '68:a8:6d', vendor: 'Apple',   type: 'computer' },
  { prefix: '6c:40:08', vendor: 'Apple',   type: 'phone'    },
  { prefix: '70:56:81', vendor: 'Apple',   type: 'computer' },
  { prefix: '70:73:cb', vendor: 'Apple',   type: 'phone'    },
  { prefix: '7c:04:d0', vendor: 'Apple',   type: 'computer' },
  { prefix: '80:e6:50', vendor: 'Apple',   type: 'phone'    },
  { prefix: '84:38:35', vendor: 'Apple',   type: 'phone'    },
  { prefix: '8c:58:77', vendor: 'Apple',   type: 'phone'    },
  { prefix: '90:3c:92', vendor: 'Apple',   type: 'phone'    },
  { prefix: '94:bf:2d', vendor: 'Apple',   type: 'computer' },
  { prefix: '98:01:a7', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'a4:5e:60', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'a8:96:8a', vendor: 'Apple',   type: 'computer' },
  { prefix: 'ac:87:a3', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'b0:9f:ba', vendor: 'Apple',   type: 'computer' },
  { prefix: 'b4:f0:ab', vendor: 'Apple',   type: 'computer' },
  { prefix: 'b8:e8:56', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'bc:52:b7', vendor: 'Apple',   type: 'computer' },
  { prefix: 'c8:2a:14', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'cc:20:e8', vendor: 'Apple',   type: 'computer' },
  { prefix: 'd0:03:4b', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'd4:61:9d', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'dc:2b:2a', vendor: 'Apple',   type: 'computer' },
  { prefix: 'e0:ac:cb', vendor: 'Apple',   type: 'computer' },
  { prefix: 'e4:ce:8f', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'e8:04:0b', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'f0:18:98', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'f4:37:b7', vendor: 'Apple',   type: 'computer' },
  { prefix: 'f8:1e:df', vendor: 'Apple',   type: 'phone'    },
  { prefix: 'fc:25:3f', vendor: 'Apple',   type: 'phone'    },
  // Samsung
  { prefix: '00:12:47', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:15:99', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:17:c9', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:1a:8a', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:1d:25', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:21:19', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:23:39', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:23:d6', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:24:90', vendor: 'Samsung', type: 'phone' },
  { prefix: '00:26:37', vendor: 'Samsung', type: 'phone' },
  { prefix: '08:08:c2', vendor: 'Samsung', type: 'phone' },
  { prefix: '08:ec:a9', vendor: 'Samsung', type: 'phone' },
  { prefix: '0c:14:20', vendor: 'Samsung', type: 'phone' },
  { prefix: '14:49:e0', vendor: 'Samsung', type: 'phone' },
  { prefix: '20:64:32', vendor: 'Samsung', type: 'phone' },
  { prefix: '28:98:7b', vendor: 'Samsung', type: 'phone' },
  { prefix: '30:19:66', vendor: 'Samsung', type: 'phone' },
  { prefix: '34:23:ba', vendor: 'Samsung', type: 'phone' },
  { prefix: '38:aa:3c', vendor: 'Samsung', type: 'phone' },
  { prefix: '3c:5a:37', vendor: 'Samsung', type: 'phone' },
  { prefix: '40:0e:85', vendor: 'Samsung', type: 'phone' },
  { prefix: '44:f4:59', vendor: 'Samsung', type: 'phone' },
  { prefix: '4c:3c:16', vendor: 'Samsung', type: 'phone' },
  { prefix: '50:01:bb', vendor: 'Samsung', type: 'phone' },
  { prefix: '54:88:0e', vendor: 'Samsung', type: 'phone' },
  { prefix: '58:ef:68', vendor: 'Samsung', type: 'phone' },
  { prefix: '5c:49:79', vendor: 'Samsung', type: 'phone' },
  { prefix: '60:a1:0a', vendor: 'Samsung', type: 'phone' },
  { prefix: '64:77:91', vendor: 'Samsung', type: 'phone' },
  { prefix: '68:27:37', vendor: 'Samsung', type: 'phone' },
  { prefix: '6c:2f:2c', vendor: 'Samsung', type: 'phone' },
  { prefix: '78:1f:db', vendor: 'Samsung', type: 'phone' },
  { prefix: '80:65:6d', vendor: 'Samsung', type: 'phone' },
  { prefix: '84:25:db', vendor: 'Samsung', type: 'phone' },
  { prefix: '88:32:9b', vendor: 'Samsung', type: 'phone' },
  { prefix: '8c:77:12', vendor: 'Samsung', type: 'phone' },
  { prefix: '94:76:b7', vendor: 'Samsung', type: 'phone' },
  { prefix: '98:39:8e', vendor: 'Samsung', type: 'phone' },
  { prefix: '9c:3a:af', vendor: 'Samsung', type: 'phone' },
  { prefix: 'a0:0b:ba', vendor: 'Samsung', type: 'phone' },
  { prefix: 'a4:eb:d3', vendor: 'Samsung', type: 'phone' },
  { prefix: 'b4:79:a7', vendor: 'Samsung', type: 'phone' },
  { prefix: 'b8:5e:7b', vendor: 'Samsung', type: 'phone' },
  { prefix: 'bc:14:85', vendor: 'Samsung', type: 'phone' },
  { prefix: 'c4:42:02', vendor: 'Samsung', type: 'phone' },
  { prefix: 'cc:07:ab', vendor: 'Samsung', type: 'phone' },
  { prefix: 'd0:22:be', vendor: 'Samsung', type: 'phone' },
  { prefix: 'd4:88:90', vendor: 'Samsung', type: 'phone' },
  { prefix: 'dc:71:96', vendor: 'Samsung', type: 'phone' },
  { prefix: 'e4:40:e2', vendor: 'Samsung', type: 'phone' },
  { prefix: 'e8:50:8b', vendor: 'Samsung', type: 'phone' },
  { prefix: 'f0:25:b7', vendor: 'Samsung', type: 'phone' },
  { prefix: 'f4:09:d8', vendor: 'Samsung', type: 'phone' },
  { prefix: 'fc:00:12', vendor: 'Samsung', type: 'phone' },
  // Xiaomi
  { prefix: '00:9e:c8', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '0c:1d:af', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '10:2a:b3', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: '14:f6:5a', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '20:34:fb', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '28:6c:07', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '34:80:b3', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '38:a4:ed', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '40:31:3c', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: '44:78:3e', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '50:8f:4c', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '58:44:98', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '5c:e8:eb', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '64:09:80', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '64:b4:73', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '68:df:dd', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '6c:93:08', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: '74:51:ba', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '78:02:f8', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '78:11:dc', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: '7c:1d:d9', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '84:a9:38', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '8c:be:be', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '94:fb:29', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: '98:fa:e3', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: 'a0:86:c6', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'ac:c1:ee', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'b0:e4:d5', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'c4:0b:cb', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'c8:9b:2c', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: 'd4:97:0b', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'e4:46:da', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'f0:b4:29', vendor: 'Xiaomi',  type: 'iot'   },
  { prefix: 'f4:8b:32', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'f8:a4:5f', vendor: 'Xiaomi',  type: 'phone' },
  { prefix: 'fc:64:ba', vendor: 'Xiaomi',  type: 'phone' },
  // Huawei
  { prefix: '00:18:82', vendor: 'Huawei',  type: 'phone' },
  { prefix: '00:1e:10', vendor: 'Huawei',  type: 'phone' },
  { prefix: '00:25:9e', vendor: 'Huawei',  type: 'router' },
  { prefix: '04:02:1f', vendor: 'Huawei',  type: 'phone' },
  { prefix: '0c:37:dc', vendor: 'Huawei',  type: 'phone' },
  { prefix: '10:1b:54', vendor: 'Huawei',  type: 'phone' },
  { prefix: '14:b9:68', vendor: 'Huawei',  type: 'phone' },
  { prefix: '1c:1d:86', vendor: 'Huawei',  type: 'phone' },
  { prefix: '20:a6:80', vendor: 'Huawei',  type: 'phone' },
  { prefix: '28:31:52', vendor: 'Huawei',  type: 'phone' },
  { prefix: '2c:ab:00', vendor: 'Huawei',  type: 'phone' },
  { prefix: '30:74:96', vendor: 'Huawei',  type: 'phone' },
  { prefix: '34:29:12', vendor: 'Huawei',  type: 'phone' },
  { prefix: '38:bc:01', vendor: 'Huawei',  type: 'phone' },
  { prefix: '40:4d:8e', vendor: 'Huawei',  type: 'phone' },
  { prefix: '44:6e:e5', vendor: 'Huawei',  type: 'phone' },
  { prefix: '48:db:50', vendor: 'Huawei',  type: 'phone' },
  { prefix: '4c:54:99', vendor: 'Huawei',  type: 'phone' },
  { prefix: '54:51:1b', vendor: 'Huawei',  type: 'phone' },
  { prefix: '58:2a:f7', vendor: 'Huawei',  type: 'phone' },
  { prefix: '60:de:44', vendor: 'Huawei',  type: 'phone' },
  { prefix: '70:7b:e8', vendor: 'Huawei',  type: 'phone' },
  { prefix: '74:a5:28', vendor: 'Huawei',  type: 'phone' },
  { prefix: '78:1d:ba', vendor: 'Huawei',  type: 'phone' },
  { prefix: '7c:60:97', vendor: 'Huawei',  type: 'phone' },
  { prefix: '80:d0:9b', vendor: 'Huawei',  type: 'phone' },
  { prefix: '84:47:09', vendor: 'Huawei',  type: 'phone' },
  { prefix: '88:cf:98', vendor: 'Huawei',  type: 'phone' },
  { prefix: '8c:34:fd', vendor: 'Huawei',  type: 'phone' },
  { prefix: '90:17:ac', vendor: 'Huawei',  type: 'phone' },
  { prefix: '94:04:9c', vendor: 'Huawei',  type: 'phone' },
  { prefix: '9c:52:f8', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'a4:50:46', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'b0:e5:ed', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'c0:70:09', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'c4:07:2f', vendor: 'Huawei',  type: 'router' },
  { prefix: 'cc:96:a0', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'd0:7a:b5', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'd4:6a:6a', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'e8:4d:d0', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'f0:79:59', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'f4:8e:38', vendor: 'Huawei',  type: 'phone' },
  { prefix: 'f8:3d:ff', vendor: 'Huawei',  type: 'phone' },
  // Windows/Intel
  { prefix: '00:0c:29', vendor: 'VMware',   type: 'computer' },
  { prefix: '00:1c:c0', vendor: 'Intel',    type: 'computer' },
  { prefix: '00:21:6a', vendor: 'Intel',    type: 'computer' },
  { prefix: '00:27:10', vendor: 'Intel',    type: 'computer' },
  { prefix: '10:02:b5', vendor: 'Intel',    type: 'computer' },
  { prefix: '18:03:73', vendor: 'Intel',    type: 'computer' },
  { prefix: '24:77:03', vendor: 'Intel',    type: 'computer' },
  { prefix: '28:d2:44', vendor: 'Intel',    type: 'computer' },
  { prefix: '3c:a9:f4', vendor: 'Intel',    type: 'computer' },
  { prefix: '40:25:c2', vendor: 'Intel',    type: 'computer' },
  { prefix: '44:85:00', vendor: 'Intel',    type: 'computer' },
  { prefix: '48:2a:e3', vendor: 'Intel',    type: 'computer' },
  { prefix: '4c:eb:42', vendor: 'Intel',    type: 'computer' },
  { prefix: '50:76:af', vendor: 'Intel',    type: 'computer' },
  { prefix: '54:27:1e', vendor: 'Intel',    type: 'computer' },
  { prefix: '5c:c5:d4', vendor: 'Intel',    type: 'computer' },
  { prefix: '60:67:20', vendor: 'Intel',    type: 'computer' },
  { prefix: '68:05:ca', vendor: 'Intel',    type: 'computer' },
  { prefix: '70:77:81', vendor: 'Intel',    type: 'computer' },
  { prefix: '7c:5c:f8', vendor: 'Intel',    type: 'computer' },
  { prefix: '80:19:34', vendor: 'Intel',    type: 'computer' },
  { prefix: '84:3a:4b', vendor: 'Intel',    type: 'computer' },
  { prefix: '90:78:41', vendor: 'Intel',    type: 'computer' },
  { prefix: '94:65:9c', vendor: 'Intel',    type: 'computer' },
  { prefix: '98:4f:ee', vendor: 'Intel',    type: 'computer' },
  { prefix: '9c:da:3e', vendor: 'Intel',    type: 'computer' },
  { prefix: 'a0:a8:cd', vendor: 'Intel',    type: 'computer' },
  { prefix: 'a4:c3:f0', vendor: 'Intel',    type: 'computer' },
  { prefix: 'ac:7b:a1', vendor: 'Intel',    type: 'computer' },
  { prefix: 'b4:b6:86', vendor: 'Intel',    type: 'computer' },
  { prefix: 'b8:08:cf', vendor: 'Intel',    type: 'computer' },
  { prefix: 'c0:cb:38', vendor: 'Intel',    type: 'computer' },
  { prefix: 'c4:d9:87', vendor: 'Intel',    type: 'computer' },
  { prefix: 'cc:3d:82', vendor: 'Intel',    type: 'computer' },
  { prefix: 'd0:57:7b', vendor: 'Intel',    type: 'computer' },
  { prefix: 'd4:3d:7e', vendor: 'Intel',    type: 'computer' },
  { prefix: 'd8:fc:93', vendor: 'Intel',    type: 'computer' },
  { prefix: 'e8:6a:64', vendor: 'Intel',    type: 'computer' },
  { prefix: 'ec:f4:bb', vendor: 'Intel',    type: 'computer' },
  // Google / Android
  { prefix: '00:1a:11', vendor: 'Google',   type: 'iot' },
  { prefix: '08:9e:08', vendor: 'Google',   type: 'iot' },
  { prefix: '18:b4:30', vendor: 'Google',   type: 'iot' },
  { prefix: '20:df:b9', vendor: 'Google',   type: 'iot' },
  { prefix: '30:fd:38', vendor: 'Google',   type: 'iot' },
  { prefix: '40:4e:36', vendor: 'Google',   type: 'iot' },
  { prefix: '48:d6:d5', vendor: 'Google',   type: 'iot' },
  { prefix: '54:60:09', vendor: 'Google',   type: 'iot' },
  { prefix: '6c:ad:f8', vendor: 'Google',   type: 'iot' },
  { prefix: '70:9f:2d', vendor: 'Google',   type: 'iot' },
  { prefix: '94:eb:2c', vendor: 'Google',   type: 'iot' },
  { prefix: 'a4:77:33', vendor: 'Google',   type: 'iot' },
  { prefix: 'dc:ef:09', vendor: 'Google',   type: 'iot' },
  { prefix: 'f4:f5:d8', vendor: 'Google',   type: 'iot' },
  // Amazon (Echo, Fire TV)
  { prefix: '00:bb:3a', vendor: 'Amazon',   type: 'iot' },
  { prefix: '04:a1:51', vendor: 'Amazon',   type: 'iot' },
  { prefix: '0c:47:c9', vendor: 'Amazon',   type: 'iot' },
  { prefix: '18:74:2e', vendor: 'Amazon',   type: 'iot' },
  { prefix: '1c:12:b0', vendor: 'Amazon',   type: 'iot' },
  { prefix: '34:d2:70', vendor: 'Amazon',   type: 'iot' },
  { prefix: '40:b4:cd', vendor: 'Amazon',   type: 'iot' },
  { prefix: '44:65:0d', vendor: 'Amazon',   type: 'iot' },
  { prefix: '50:f5:da', vendor: 'Amazon',   type: 'iot' },
  { prefix: '68:37:e9', vendor: 'Amazon',   type: 'iot' },
  { prefix: '74:75:48', vendor: 'Amazon',   type: 'iot' },
  { prefix: '84:d6:d0', vendor: 'Amazon',   type: 'iot' },
  { prefix: 'a0:02:dc', vendor: 'Amazon',   type: 'iot' },
  { prefix: 'ac:63:be', vendor: 'Amazon',   type: 'iot' },
  { prefix: 'b4:7c:9c', vendor: 'Amazon',   type: 'iot' },
  { prefix: 'cc:9e:a2', vendor: 'Amazon',   type: 'iot' },
  { prefix: 'f0:27:65', vendor: 'Amazon',   type: 'iot' },
  { prefix: 'fc:a6:67', vendor: 'Amazon',   type: 'iot' },
  // Raspberry Pi / SBC
  { prefix: 'b8:27:eb', vendor: 'Raspberry Pi', type: 'computer' },
  { prefix: 'dc:a6:32', vendor: 'Raspberry Pi', type: 'computer' },
  { prefix: 'e4:5f:01', vendor: 'Raspberry Pi', type: 'computer' },
  // Synology NAS
  { prefix: '00:11:32', vendor: 'Synology', type: 'nas' },
  { prefix: '00:ab:ab', vendor: 'Synology', type: 'nas' },
  // QNAP NAS
  { prefix: '00:08:9b', vendor: 'QNAP',     type: 'nas' },
  { prefix: '24:5e:be', vendor: 'QNAP',     type: 'nas' },
  { prefix: '00:1a:a2', vendor: 'QNAP',     type: 'nas' },
  // TP-Link
  { prefix: '00:1d:0f', vendor: 'TP-Link',  type: 'router' },
  { prefix: '14:cc:20', vendor: 'TP-Link',  type: 'router' },
  { prefix: '18:a6:f7', vendor: 'TP-Link',  type: 'router' },
  { prefix: '1c:61:b4', vendor: 'TP-Link',  type: 'router' },
  { prefix: '24:a4:3c', vendor: 'TP-Link',  type: 'router' },
  { prefix: '30:b5:c2', vendor: 'TP-Link',  type: 'router' },
  { prefix: '38:94:ed', vendor: 'TP-Link',  type: 'router' },
  { prefix: '40:16:9f', vendor: 'TP-Link',  type: 'router' },
  { prefix: '44:ad:d9', vendor: 'TP-Link',  type: 'router' },
  { prefix: '50:c7:bf', vendor: 'TP-Link',  type: 'router' },
  { prefix: '54:a7:03', vendor: 'TP-Link',  type: 'router' },
  { prefix: '60:a4:b7', vendor: 'TP-Link',  type: 'router' },
  { prefix: '64:70:02', vendor: 'TP-Link',  type: 'router' },
  { prefix: '74:da:38', vendor: 'TP-Link',  type: 'router' },
  { prefix: '80:8f:1d', vendor: 'TP-Link',  type: 'router' },
  { prefix: '8c:a6:df', vendor: 'TP-Link',  type: 'router' },
  { prefix: '90:f6:52', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'a4:2b:b0', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'b0:95:8e', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'c4:6e:1f', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'd4:6e:0e', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'e8:de:27', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'ec:08:6b', vendor: 'TP-Link',  type: 'router' },
  { prefix: 'f8:1a:67', vendor: 'TP-Link',  type: 'router' },
  // GL.iNet
  { prefix: '94:83:c4', vendor: 'GL.iNet',  type: 'router' },
  { prefix: 'a8:5e:45', vendor: 'GL.iNet',  type: 'router' },
  { prefix: 'd4:da:21', vendor: 'GL.iNet',  type: 'router' },
  { prefix: '00:1f:7b', vendor: 'GL.iNet',  type: 'router' },
  // Espressif (ESP8266/ESP32 IoT chips)
  { prefix: '18:fe:34', vendor: 'Espressif', type: 'iot' },
  { prefix: '24:0a:c4', vendor: 'Espressif', type: 'iot' },
  { prefix: '2c:3a:e8', vendor: 'Espressif', type: 'iot' },
  { prefix: '30:ae:a4', vendor: 'Espressif', type: 'iot' },
  { prefix: '3c:71:bf', vendor: 'Espressif', type: 'iot' },
  { prefix: '40:f5:20', vendor: 'Espressif', type: 'iot' },
  { prefix: '4c:11:ae', vendor: 'Espressif', type: 'iot' },
  { prefix: '54:43:b2', vendor: 'Espressif', type: 'iot' },
  { prefix: '5c:cf:7f', vendor: 'Espressif', type: 'iot' },
  { prefix: '60:01:94', vendor: 'Espressif', type: 'iot' },
  { prefix: '68:c6:3a', vendor: 'Espressif', type: 'iot' },
  { prefix: '70:03:9f', vendor: 'Espressif', type: 'iot' },
  { prefix: '7c:9e:bd', vendor: 'Espressif', type: 'iot' },
  { prefix: '80:7d:3a', vendor: 'Espressif', type: 'iot' },
  { prefix: '84:0d:8e', vendor: 'Espressif', type: 'iot' },
  { prefix: '84:cc:a8', vendor: 'Espressif', type: 'iot' },
  { prefix: '88:13:bf', vendor: 'Espressif', type: 'iot' },
  { prefix: '8c:aa:b5', vendor: 'Espressif', type: 'iot' },
  { prefix: 'a4:7b:9d', vendor: 'Espressif', type: 'iot' },
  { prefix: 'ac:67:b2', vendor: 'Espressif', type: 'iot' },
  { prefix: 'b4:e6:2d', vendor: 'Espressif', type: 'iot' },
  { prefix: 'bc:dd:c2', vendor: 'Espressif', type: 'iot' },
  { prefix: 'c4:4f:33', vendor: 'Espressif', type: 'iot' },
  { prefix: 'cc:50:e3', vendor: 'Espressif', type: 'iot' },
  { prefix: 'd8:a0:1d', vendor: 'Espressif', type: 'iot' },
  { prefix: 'dc:4f:22', vendor: 'Espressif', type: 'iot' },
  { prefix: 'e8:db:84', vendor: 'Espressif', type: 'iot' },
  { prefix: 'ec:fa:bc', vendor: 'Espressif', type: 'iot' },
  { prefix: 'f4:cf:a2', vendor: 'Espressif', type: 'iot' },
  // Tuya / Broadlink (Smart Home)
  { prefix: 'b0:f8:93', vendor: 'Tuya',     type: 'iot' },
  { prefix: 'd8:96:e0', vendor: 'Tuya',     type: 'iot' },
  { prefix: '00:1b:fc', vendor: 'Broadlink', type: 'iot' },
  // OnePlus
  { prefix: '00:04:f2', vendor: 'OnePlus',  type: 'phone' },
  { prefix: '94:65:2d', vendor: 'OnePlus',  type: 'phone' },
  { prefix: 'ac:37:43', vendor: 'OnePlus',  type: 'phone' },
  // Realme / OPPO
  { prefix: '00:0e:35', vendor: 'OPPO',     type: 'phone' },
  { prefix: '18:1e:78', vendor: 'OPPO',     type: 'phone' },
  { prefix: '28:ba:b5', vendor: 'OPPO',     type: 'phone' },
  { prefix: '4c:dd:31', vendor: 'OPPO',     type: 'phone' },
  { prefix: '5c:31:3e', vendor: 'OPPO',     type: 'phone' },
  { prefix: '74:e2:0c', vendor: 'OPPO',     type: 'phone' },
  { prefix: 'a0:af:bd', vendor: 'OPPO',     type: 'phone' },
  { prefix: 'b4:a9:fc', vendor: 'OPPO',     type: 'phone' },
  { prefix: 'c0:ee:fb', vendor: 'OPPO',     type: 'phone' },
];

// Build lookup: normalize prefix to lowercase 8-char (xx:xx:xx)
const _lookup = new Map();
for (const entry of OUI_MAP) {
  _lookup.set(entry.prefix.toLowerCase(), entry);
}

/**
 * Look up a MAC address → { vendor, type } or null
 */
function lookup(mac) {
  if (!mac) return null;
  const norm = mac.toLowerCase().replace(/-/g, ':');
  const prefix = norm.slice(0, 8);
  return _lookup.get(prefix) || null;
}

/**
 * Get display icon for device type
 */
const TYPE_ICONS = {
  phone:    '📱',
  computer: '💻',
  router:   '📡',
  iot:      '🔌',
  nas:      '🖥️',
  unknown:  '❓',
};

function typeIcon(type) {
  return TYPE_ICONS[type] || TYPE_ICONS.unknown;
}

module.exports = { lookup, typeIcon, TYPE_ICONS };
